
plugins:
  - jekyll-redirect-from
  
#-- Permalinks
permalink:        pretty

future:           true

#-- Setup
title:            TU Delft MSc Geomatics graduation thesis
url:              "https://3d.bk.tudelft.nl"
baseurl:          "/courses/geo2020"


